prompt = """
Step 1:
list_adks

Step 2:
請根據 list_adks 列出來的 adk list 挑選一個跟  `{{args}}` 最為類似的，然後再使用 list_adk_agent

Step 3:
請根據 list_adk_agent 列出來的 agent list 挑選一個跟 `{{args}}` 最為類似的，然後再使用 create_session 初始化對話，取得 session_id，然後進行 send_message_to_agent
"""